default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.18
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--frozen"]
      - id: uv-sync
        args: ["--locked"]
