default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite


default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  # 1. Lock the dependencies
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.18
    hooks:
      - id: uv-lock
        name: Lock Dependencies
        files: ^requirements\.(in|txt)$

  # 2. Export the lock file to requirements.txt
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.18
    hooks:
      - id: uv-export
        name: Export Lock to requirements.txt

  # 3. Compile requirements.in to requirements.txt
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.18
    hooks:
      - id: pip-compile
        name: Compile requirements.in to requirements.txt
        args: [requirements.in, -o, requirements.txt]