default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.18
    hooks:
      - id: uv-lock
        files: ^requirements\.(in|txt)$
        args: [--lockfile=requirements.lock]
      - id: uv-sync
        args: [--lockfile=requirements.lock]
  - repo: local
    hooks:
      - id: check-requirements
        name: Check and Install Requirements
        entry: python scripts/update_dependencies.py
        language: python
        files: requirements.txt
        pass_filenames: false
